### ISSUE TITLE
Setup project locally

### ISSUE THREAD

**Issue by olakehinde** [KarenOk/whatsapp-web-clone#1]
Hi there,
Could you kindly put in the readme, the steps necessary to run this project locally? At least for the sake of non-React folks like me, just to test and see how this runs locally.

**Comment by KarenOk** [comment]
Alrighty. Will do.

**Comment by PiranhaHunter** [comment]
> Hi there,
> Could you kindly put in the readme, the steps necessary to run this project locally? At least for the sake of non-React folks like me, just to test and see how this runs locally.

To build and run this project locally:

1. Download and Install Node JS from https://nodejs.org/en/download/
2. In the root project directory, type ```npm install``` to build the project.
3. Once build is completed, type ```npm start``` to start the project in your local browser.
