### ISSUE TITLE
Spacing at the bottom of the chat

### ISSUE THREAD

**Issue by Avni1802** [KarenOk/whatsapp-web-clone#3]
There is extra spacing at the end of the chat. Which looks a bit untidy. Also, it doesn't match the original WhatsApp web UI.

![Screenshot (195)_LI](https://user-images.githubusercontent.com/59050786/123140926-7985b500-d475-11eb-99c2-7547487fbc51.jpg)

**Comment by Avni1802** [comment]
I can resolve this issue. Shall I?

**Comment by KarenOk** [comment]
I don't believe it's a such significant issue.
